name: Terraform Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init
        run: terraform init
        working-directory: awselz/awselz/module/ec2/

      - name: Plan
        run: terraform plan -out=tfplan
        working-directory: awselz/awselz/module/ec2/

      - name: Apply
        run: terraform apply -auto-approve tfplan
        working-directory: awselz/awselz/module/ec2/
