name: Terraform Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Debug - list files
        run: ls -R
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Init
        run: terraform init
        working-directory: modules/ec2/

      - name: Plan
        run: terraform plan -out=tfplan
        working-directory: modules/ec2/

      - name: Apply
        run: terraform apply -auto-approve tfplan
        working-directory: modules/ec2/
